bind-address: :8888
enable-pprof: true
kafka:
  client-id: {{.MQ.BinaryName}}
  #username: 
  #password: 
  brokers:
    - localhost:9092
  compressed: false # 本地调试通常不开启压缩，方便查看 payload
  tls:
    use-tls: false
  writer:
    max-attempts: 3
    required-acks: 1       # Leader 确认即可，追求速度
    async: true
    batch-bytes: 1048576   # 1MB
    batch-timeout: "1s"
  reader:
    group-id: "my-service-group-dev"
    min-bytes: 1024        # 1KB
    max-bytes: 10485760    # 10MB
    max-wait: "5s"
    start-offset: -1       # 从最新位置开始消费 (Latest)
{{- if .MQ.WithOTel }}
otel:
  endpoint: 127.0.0.1:4327
  service-name: {{.MQ.BinaryName}}
  # 支持 otel、console、file、slog、classic、hybrid：
  # - otel:
  #   - logs -> otel collector agent
  #   - metrics -> otel collector agent
  #   - traces -> otel collector agent
  # - file:
  #   - logs -> 以 opentelemetry 格式，输出到 <output-dir>/logs.json 文件中
  #   - metrics -> 以 opentelemetry 格式，输出到 <output-dir>/metrics.json 文件中
  #   - traces -> 以 opentelemetry 格式，输出到 <output-dir>/traces.json 文件中
  # - console:
  #   - logs -> 以 opentelemetry 格式，输出到标准输出中
  #   - metrics -> 以 opentelemetry 格式，输出到标准输出中
  #   - traces -> 以 opentelemetry 格式，输出到标准输出中
  # - classic:
  #   - logs -> 输出到标准输出中（自定义结构化日志）
  #   - metrics -> 输出到 promethus export 中
  #   - traces -> 关闭 trace
  # - hybrid:
  #   - logs -> 输出到标准输出中（自定义结构化日志）
  #   - metrics -> 输出到 promethus export 中
  #   - traces -> 输出到 otel collector agent 中
  # output-dir: ./otel # file mode 下，文件输出路径
  output-mode: classic
  level: debug
  add-source: false
  slog: # 该配置项只有 output-mode 为 hybrid, classic 时生效
    format: json
    time-format: "2006-01-02 15:04:05"
    output: stdout # 支持 stdout, stderr, or file path
{{- else }}
slog:
  level: debug # 支持 error, warn, info, debug
  add-source: false
  format: json # 支持 json 和text
  time-format: "2006-01-02 15:04:05"
  output: stdout # 支持 stdout 和文件路径
{{- end}}
{{- if or (eq .MQ.StorageType "mysql") (eq .MQ.StorageType "mariadb") }}
mysql:
  addr: 127.0.0.1:3306
  username: onex
  password: "onex(#)666"
  database: onex
{{- end}}
{{- range .MQ.Clients }}
{{.}}:
  # {{.}} 访问地址
  endpoint: http://127.0.0.1:9999
  # 访问 {{.}} 时的 User-Agent
  user-agent: {{$.MQ.BinaryName}}
  # 开启 resty 客户端的 debug 模式
  debug: true
  # 访问远端服务时的超时时间
  timeout: 30s
{{- end -}}
