{{- $D := or .Web .MQ .Job -}}
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameJobM = "{{$D.BinaryName | extractProjectPrefix}}_job"

// JobM 任务表
type JobM struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键 ID" json:"id"`                     // 主键 ID
	JobID       string         `gorm:"column:job_id;not null;comment:Job ID" json:"job_id"`                                 // Job ID
	Username    string         `gorm:"column:username;not null;comment:用户名" json:"username"`                                // 用户名
	Scope       string         `gorm:"column:scope;not null;default:default;comment:Job 作用域" json:"scope"`                  // Job 作用域
	Name        string         `gorm:"column:name;not null;comment:Job 名称" json:"name"`                                     // Job 名称
	Description string         `gorm:"column:description;not null;comment:Job 描述" json:"description"`                       // Job 描述
	CronJobID   *string        `gorm:"column:cronjob_id;comment:CronJob ID，可选" json:"cronjob_id"`                         // CronJob ID，可选
	Watcher     string         `gorm:"column:watcher;not null;comment:mb-job watcher 名字" json:"watcher"`                    // mb-job watcher 名字
	Suspend     int32          `gorm:"column:suspend;not null;comment:是否挂起（1 挂起，0 不挂起）" json:"suspend"`                     // 是否挂起（1 挂起，0 不挂起）
	Params      *JobParams     `gorm:"column:params;comment:Job 参数" json:"params"`                                          // Job 参数
	Results     *JobResults    `gorm:"column:results;comment:Job 执行结果" json:"results"`                                      // Job 执行结果
	Status      string         `gorm:"column:status;not null;default:Pending;comment:Job 状态" json:"status"`                 // Job 状态
	Conditions  *JobConditions `gorm:"column:conditions;comment:Job 运行状态" json:"conditions"`                                // Job 运行状态
	StartedAt   *time.Time     `gorm:"column:started_at;default:null;comment:Job 开始时间" json:"started_at"`                   // Job 开始时间
	EndedAt     *time.Time     `gorm:"column:ended_at;default:null;comment:Job 结束时间" json:"ended_at"`                       // Job 结束时间
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // Job 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // Job 更新时间
}

// TableName JobM's table name
func (*JobM) TableName() string {
	return TableNameJobM
}
