{{- $D := or .Web .MQ .Job -}}
// This file defines the Protobuf messages for managing {{$D.R.PluralName}}.
//
syntax = "proto3"; // Specifies the syntax version used in this file.

package {{$D.Name}}.{{.M.APIVersion}};

import "google/protobuf/timestamp.proto"; // Importing Google's timestamp type for date/time fields.

// Specifies the Go package for generated code.
option go_package = "{{.M.ModuleName}}/pkg/api/{{$D.Name}}/{{.M.APIVersion}};{{.M.APIVersion}}";

// {{$D.R.SingularName}} represents a {{$D.R.SingularLower}} with its metadata.
message {{$D.R.SingularName}} {
    // {{$D.R.SingularName}}ID is the unique identifier for the {{$D.R.SingularLower}}.
    string {{$D.R.SingularLowerFirst}}ID = 1;
    // CreatedAt is the timestamp when the {{$D.R.SingularLower}} was created.
    google.protobuf.Timestamp createdAt = 2;
    // UpdatedAt is the timestamp when the {{$D.R.SingularLower}} was last updated.
    google.protobuf.Timestamp updatedAt = 3;
    // TODO: Add additional fields if needed.
}

// Create{{$D.R.SingularName}}Request represents the request message for creating a new {{$D.R.SingularLower}}.
message Create{{$D.R.SingularName}}Request {
    // TODO: Add additional fields if needed.
}

// Create{{$D.R.SingularName}}Response represents the response message for a successful {{$D.R.SingularLower}} creation.
message Create{{$D.R.SingularName}}Response {
    // {{$D.R.SingularName}}ID is the unique identifier of the newly created {{$D.R.SingularLower}}.
    string {{$D.R.SingularLowerFirst}}ID = 1;
    // TODO: Add additional fields to return if needed.
}

// Update{{$D.R.SingularName}}Request represents the request message for updating an existing {{$D.R.SingularLower}}.
message Update{{$D.R.SingularName}}Request {
    // {{$D.R.SingularName}}ID is the unique identifier of the {{$D.R.SingularLower}} to update.
    // @gotags: uri:"{{$D.R.SingularLowerFirst}}ID"
    string {{$D.R.SingularLowerFirst}}ID = 1;
    // TODO: Add additional fields to update if needed.
}

// Update{{$D.R.SingularName}}Response represents the response message for a successful {{$D.R.SingularLower}} update.
message Update{{$D.R.SingularName}}Response {
    // TODO: Add additional fields to return if needed.
}

// Delete{{$D.R.SingularName}}Request represents the request message for delete a single {{$D.R.SingularName}} specified by a URI parameter.
message Delete{{$D.R.SingularName}}Request {
    // {{$D.R.SingularName}}ID is the unique identifier for the {{$D.R.SingularLower}} to delete.
    // @gotags: uri:"{{$D.R.SingularLowerFirst}}ID"
    string {{$D.R.SingularLowerFirst}}ID = 1;
    // TODO: Add additional fields if needed.
}

// Delete{{$D.R.SingularName}}Response represents the response message for a successful {{$D.R.SingularName}} deletion.
message Delete{{$D.R.SingularName}}Response {
    // TODO: Add additional fields to return if needed.
}

// Delete{{$D.R.PluralName}}Request represents the request message for deleting one or more {{$D.R.PluralLower}}.
message Delete{{$D.R.PluralName}}Request {
    // {{$D.R.SingularName}}IDs is the list of unique identifiers for the {{$D.R.PluralLower}} to delete.
    repeated string {{$D.R.SingularLowerFirst}}IDs = 1;
    // TODO: Add additional fields if needed.
}

// Delete{{$D.R.PluralName}}Response represents the response message for a successful {{$D.R.PluralLower}} deletion.
message Delete{{$D.R.PluralName}}Response {
    // TODO: Add additional fields to return if needed.
}

// Get{{$D.R.SingularName}}Request represents the request message for retrieving a specific {{$D.R.SingularLower}}.
message Get{{$D.R.SingularName}}Request {
    // {{$D.R.SingularName}}ID is the unique identifier of the {{$D.R.SingularLower}} to retrieve.
    // @gotags: uri:"{{$D.R.SingularLowerFirst}}ID"
    string {{$D.R.SingularLowerFirst}}ID = 1;
}

// Get{{$D.R.SingularName}}Response represents the response message for a successful retrieval of a {{$D.R.SingularLower}}.
message Get{{$D.R.SingularName}}Response {
    // {{$D.R.SingularName}} is the retrieved {{$D.R.SingularLower}} object.
    {{$D.R.SingularName}} {{$D.R.SingularLowerFirst}} = 1;
}

// List{{$D.R.SingularName}}Request represents the request message for listing {{$D.R.PluralLower}}
// with pagination and optional filters.
message List{{$D.R.SingularName}}Request {
    // Offset is the starting point of the list for pagination.
    // @gotags: form:"offset"
    int64 offset = 1;
    // Limit is the maximum number of {{$D.R.PluralLower}} to return.
    // @gotags: form:"limit"
    int64 limit = 2;
    // TODO: Add additional query fields if needed.
}

// List{{$D.R.SingularName}}Response represents the response message for listing {{$D.R.PluralLower}}.
message List{{$D.R.SingularName}}Response {
    // TotalCount is the total number of {{$D.R.PluralLower}} matching the query.
    int64 total = 1;
    // {{$D.R.SingularName}} is the list of {{$D.R.PluralLower}} in the current page.
    repeated {{$D.R.SingularName}} {{$D.R.PluralLowerFirst}} = 2;
}
